googleapis/nodejs-dialogflow

samples/README.md

Clarify README "before you begin" section

---

.github/ISSUE_TEMPLATE.md
.gitignore
.mailmap
CONTRIBUTORS
README.md
package-lock.json
package.json
samples/README.md
samples/package-lock.json

Regenerated `README.md` and other stuff.

docs: regenerated scaffolding

---

protos/google/cloud/dialogflow/v2beta1/agent.proto
protos/google/cloud/dialogflow/v2beta1/context.proto
protos/google/cloud/dialogflow/v2beta1/entity_type.proto
protos/google/cloud/dialogflow/v2beta1/intent.proto
protos/google/cloud/dialogflow/v2beta1/session.proto
protos/google/cloud/dialogflow/v2beta1/session_entity_type.proto
protos/google/cloud/dialogflow/v2beta1/webhook.proto
src/index.js
src/v2beta1/agents_client.js
src/v2beta1/contexts_client.js
src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_agent.js
src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_context.js
src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_entity_type.js
src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_intent.js
src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_session.js
src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_session_entity_type.js
src/v2beta1/doc/google/protobuf/doc_any.js
src/v2beta1/doc/google/protobuf/doc_field_mask.js
src/v2beta1/doc/google/protobuf/doc_struct.js
src/v2beta1/doc/google/rpc/doc_status.js
src/v2beta1/doc/google/type/doc_latlng.js
src/v2beta1/entity_types_client.js
src/v2beta1/index.js
src/v2beta1/intents_client.js
src/v2beta1/session_entity_types_client.js
src/v2beta1/sessions_client.js
test/gapic-v2beta1.js

Regenerating GAPIC code for dialogflow `v2beta1`.

update GAPIC v2beta1 code

---

package-lock.json
package.json
samples/package-lock.json
samples/package.json

increment minor version

---

src/v2beta1/contexts_client.js

regenerated v2beta1

---

CONTRIBUTORS
README.md
package-lock.json
package.json
samples/README.md
src/v2/agents_client.js
src/v2/contexts_client.js
src/v2/doc/google/longrunning/doc_operations.js
src/v2/doc/google/protobuf/doc_empty.js
src/v2/entity_types_client.js
src/v2/intents_client.js
src/v2/session_entity_types_client.js
src/v2/sessions_client.js
src/v2beta1/agents_client.js
src/v2beta1/contexts_client.js
src/v2beta1/doc/google/longrunning/doc_operations.js
src/v2beta1/doc/google/protobuf/doc_empty.js
src/v2beta1/entity_types_client.js
src/v2beta1/intents_client.js
src/v2beta1/session_entity_types_client.js
src/v2beta1/sessions_client.js
synth.py

Regenerate GAPIC for V1 and V2Beta1 using synth.py

---

samples/resource.js

Per the Enum name in https://dialogflow.com/docs/reference/api-v2/rest/Shared.Types/Type
Fixes #130 
- [y ] Tests and linter pass
- [y ] Code coverage does not decrease (if any source code was changed)
- [N/A ] Appropriate docs were updated (if necessary)

Update the type of Training phases

---

CHANGELOG.md
package-lock.json
package.json
samples/package-lock.json
samples/package.json

This pull request was generated using releasetool.

Release dialogflow-nodejs-client-v2 v0.6.0

---

system-test/no-test.js

we don't have any system tests for dialogflow yet, which mocha doens't like. Let's add a dummy file to bypass that.

build: add empty file in system-test

---

test/gapic-v2.js
test/gapic-v2beta1.js

unblocks upgrade to eslint-plugin-node@^7.0.0 #135

chore: assert.equal => assert.strictEqual

---

samples/detect.js

sessi**s**on -> session 
- [N/A] Code coverage does not decrease (if any source code was changed)
- [N/A] Appropriate docs were updated (if necessary)

Fix typo in word 'session' in detect sample comments

---

samples/detect.js

Fixes #https://github.com/googleapis/nodejs-dialogflow/issues/123 (it's a good idea to open an issue first for discussion)

Fix typo in comment

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release dialogflow v0.7.0

---

README.md

Strip dynamic badges from README

---

samples/detect.js
samples/detect.v2beta1.js
samples/quickstart.js
samples/resource.js

Fixes #[2869](https://github.com/googleapis/google-cloud-node/issues/2869) partially for nodejs-dialogflow (it's a good idea to open an issue first for discussion)

docs(samples): updated samples to use async/await

---

README.md
samples/.eslintrc.yml
samples/README.md
samples/package.json
samples/quickstart.js

This gets it closer to the other samples.  Fixes #19 .

docs: improve the quickstart sample

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release dialogflow v0.8.1

---

CHANGELOG.md
package.json
samples/package.json

This pull request was generated using releasetool.

Release dialogflow v0.8.2

---

samples/README.md
samples/detect.js
samples/detect.v2beta1.js
samples/resource.js

Fixes #312, @techpeace look reasonable?

docs: fix docs 404 in samples/docs

---

samples/README.md
samples/detect.v2beta1.js

docs(samples): fix description typo

---

samples/detect-intent-TTS-response.v2.js
samples/detect-intent-sentiment.v2.js
samples/system-test/detect.test.js

TTS / Sentiment GA (handoff from Nirupa)

---

.mocharc.json
package.json
samples/system-test/create-knowledge-base.v2beta1.test.js
system-test/.eslintrc.yml
system-test/install.ts
tsconfig.json
tslint.json

... and some other minor clean up.  I'm a little worried about some autosynth weirdness I just closed out.  Hoping a version bump and a nap for synthtool helps.

fix: bump min version of dependencies

---

package.json
samples/package.json

fix: exception occurred in retry method

---

package.json
synth.py

The generator Docker image will start supporting this option soon.
The command line will be: `..... --validation false .....`

chore: disable proto validation by the generator

---

README.md

Replaced `sessionPath()` with `projectAgentSessionPath()`, since this changed in 2.x.
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- Not a code change
- Not a code change
Fixes #605  🦕

Fixes #605 - example correction
